addr: ":8080"
db_uri: "host=finger_checker-postgres-1 user=gofinger dbname=gofinger sslmode=disable password=example"
# db_uri: "host=0.0.0.0 user=gofinger dbname=gofinger sslmode=disable password=example"
